#
# stratum server cfg
#
# @since 2016-06
# @copyright btc.com
#

# is using testnet3
network: "regtest"

payout_address: mt4BFpmdbGft3Q8eQDo5ehUVNq99uzBugy

kafka:
  brokers: 1.1.1.1:9092,2.2.2.2:9092,3.3.3.3:9092

sserver:
  ip: 0.0.0.0
  port: 3333

  # should be global unique, range: [1, 255]
  id: 1

  # write last mining notify job send time to file, for monitor
  file_last_notify_time: /work/xxx/sserver_lastnotifytime.txt

  # if enable simulator, all share will be accepted. for testing
  enable_simulator: false

  # if enable it, all share will make block and submit. for testing
  enable_submit_invalid_block: false

users:
  #
  # https://example.com/get_user_id_list?last_id=0
  # {"err_no":0,"err_msg":null,"data":{"jack":1,"terry":2}}
  #
  list_id_api_url: https://example.com/get_user_id_list

#
# pool mysql db: table.mining_workers
#

pooldb:
  host: ""
  port: 3306
  username: dbusername
  password: dbpassword
  dbname: ""

gbtmaker:
  # rpc call interval seconds
  rpcinterval: 5
  # check zmq when startup
  is_check_zmq: true

bitcoind:
  # bitcoind MUST with zmq options: -zmqpubhashblock, -zmqpubhashtx
  # '-zmqpubhashtx' will use to check zmq is working when startup gbtmaker
  zmq_addr: tcp://127.0.0.1:8331
  rpc_addr: "" # http://127.0.0.1:8332
  rpc_user: "" # username
  rpc_password: "" # password

jobmaker:
  #  submit stratum job interval seconds
  stratum_job_interval: 10
  # max gbt life cycle time seconds
  gbt_life_time: 60
  # write last stratum job send time to file
  file_last_job_time: /work/xxx/jobmaker_lastjobtime.txt